/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Login: typeof import('./src/components/Login.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendMail: typeof import('./src/components/SendMail.vue')['default']
    SettingAccount: typeof import('./src/components/SettingAccount.vue')['default']
    SettingLayout: typeof import('./src/components/SettingLayout.vue')['default']
    Snackbars: typeof import('./src/components/Snackbars.vue')['default']
  }
}
